version: '3'
services:
  mongodb:
    image: mongo:latest
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: admin
    #   MONGO_INITDB_ROOT_PASSWORD: admin123
    #   MONGO_INITDB_DATABASE: booking_app
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - booking_network

  mongo-express:
    image: mongo-express:latest
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
    ports:
      - "8081:8081"
    networks:
      - booking_network
    depends_on:
      - mongodb

  booking_app-client:
    image: booking_app/client:latest
    build:
      context: client
      dockerfile: Dockerfile
    networks:
      - booking_network
    ports:
      - "3006:3006"

  booking_app-api:
    build:
      context: api
      dockerfile: Dockerfile
    environment:
      MONGO: "mongodb://mongodb:27017/booking_app"
    networks:
      - booking_network
    depends_on:
      - mongodb
    ports:
      - "8800:8800"


volumes:
  mongo_data:

networks:
  booking_network:
